package view.Bibliotecário;
import beans.emprestimo;
import beans.pedido;
import dao.emprestimoDAO;
import dao.pedidoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.TelaAjuda;
import view.TelaPerfil;
import view.TelaTipoLogin;
/**
 *
 * @author usuario
 */
public class TelaEmprestimoBibliotecario extends javax.swing.JFrame {

    private void preencheTabelaEmprestimo() {
        
        emprestimoDAO eDAO = new emprestimoDAO();
        List<emprestimo> listaEmprestimo = eDAO.preencherTabelaEmprestimo();

    DefaultTableModel tabelaEmprestimo = (DefaultTableModel) tblEmprestimo.getModel();
    tabelaEmprestimo.setNumRows(0);

    for (emprestimo e : listaEmprestimo) {
        Object[] obj = new Object[]{
            
            e.getId(),
            e.getTitulo(),
            e.getUENome(),
            e.getUINome(),
            e.getDataEmprestimo(),
            e.getDataDevolucao(),
            e.getStatus(),
            e.getChancesDePrazo()
                
        };
        tabelaEmprestimo.addRow(obj);
    }
}
    
    public TelaEmprestimoBibliotecario() {
        initComponents();
        preencheTabelaEmprestimo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tblEmprestimo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMenu = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnMenuGerenciarAcervo = new javax.swing.JMenuItem();
        mnMenuSolicitacoes = new javax.swing.JMenuItem();
        mnCadastro = new javax.swing.JMenu();
        mnCadastroUExterno = new javax.swing.JMenuItem();
        mnCadastroUInterno = new javax.swing.JMenuItem();
        mnUsuario = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pergamum");
        setMinimumSize(new java.awt.Dimension(770, 503));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Empréstimos");

        tblEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Solicitante", "Autorizador", "Data de Empréstimo", "Data de Devolução", "Status", "Renovar Prazo"
            }
        ));
        scroll.setViewportView(tblEmprestimo);

        jLabel1.setFont(new java.awt.Font("Meditative", 0, 24)); // NOI18N
        jLabel1.setText("PERGAMUM");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\coruja.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addGap(60, 60, 60)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mnMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\book.png")); // NOI18N
        mnMenu.setText("Menu");

        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\book_addresses.png")); // NOI18N
        jMenuItem5.setText("Empréstimos");
        mnMenu.add(jMenuItem5);

        mnMenuGerenciarAcervo.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\book_open.png")); // NOI18N
        mnMenuGerenciarAcervo.setText("Gerenciar Acervo");
        mnMenuGerenciarAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMenuGerenciarAcervoActionPerformed(evt);
            }
        });
        mnMenu.add(mnMenuGerenciarAcervo);

        mnMenuSolicitacoes.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\book_go.png")); // NOI18N
        mnMenuSolicitacoes.setText("Solicitações");
        mnMenuSolicitacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMenuSolicitacoesActionPerformed(evt);
            }
        });
        mnMenu.add(mnMenuSolicitacoes);

        jMenuBar1.add(mnMenu);

        mnCadastro.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\group.png")); // NOI18N
        mnCadastro.setText("Cadastro");

        mnCadastroUExterno.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\user_orange.png")); // NOI18N
        mnCadastroUExterno.setText("Cadastro de Usuário Externo");
        mnCadastroUExterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroUExternoActionPerformed(evt);
            }
        });
        mnCadastro.add(mnCadastroUExterno);

        mnCadastroUInterno.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\user_gray.png")); // NOI18N
        mnCadastroUInterno.setText("Cadastro de Usuário Interno");
        mnCadastroUInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroUInternoActionPerformed(evt);
            }
        });
        mnCadastro.add(mnCadastroUInterno);

        jMenuBar1.add(mnCadastro);

        mnUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\user.png")); // NOI18N
        mnUsuario.setText("Usuário");

        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\pencil.png")); // NOI18N
        jMenuItem3.setText("Perfil");
        mnUsuario.add(jMenuItem3);

        jMenuBar1.add(mnUsuario);

        mnAjuda.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\help.png")); // NOI18N
        mnAjuda.setText("Ajuda");
        mnAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAjudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnAjuda);

        mnSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\InterfaceJava\\src\\images\\stop.png")); // NOI18N
        mnSair.setText("Sair");
        mnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnMenuGerenciarAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMenuGerenciarAcervoActionPerformed

        dispose();
        TelaGerenciaAcervo tela = new TelaGerenciaAcervo();
        tela.setVisible(true);

    }//GEN-LAST:event_mnMenuGerenciarAcervoActionPerformed

    private void mnMenuSolicitacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMenuSolicitacoesActionPerformed

        pedidoDAO pDAO = new pedidoDAO();
        boolean pedido = pDAO.checarPedidosPendentes();

        if(pedido == true){

            TelaSolicitacao tela = new TelaSolicitacao();
            tela.setVisible(true);

        }else{

            JOptionPane.showMessageDialog(this, "Não há nenhuma solicitação pendente no momento!");

        }

    }//GEN-LAST:event_mnMenuSolicitacoesActionPerformed

    private void mnCadastroUExternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroUExternoActionPerformed

        TelaCadastroUsuarioExterno tela = new TelaCadastroUsuarioExterno();
        tela.setVisible(true);

    }//GEN-LAST:event_mnCadastroUExternoActionPerformed

    private void mnCadastroUInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroUInternoActionPerformed

        TelaCadastroBibliotecario frame = new TelaCadastroBibliotecario();
        frame.setVisible(true);

    }//GEN-LAST:event_mnCadastroUInternoActionPerformed

    private void mnAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAjudaMouseClicked

        dispose();
        TelaAjuda novaTela = new TelaAjuda();
        novaTela.setVisible(true);

    }//GEN-LAST:event_mnAjudaMouseClicked

    private void mnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSairMouseClicked

        int response = JOptionPane.showConfirmDialog(
            TelaEmprestimoBibliotecario.this,
            "Tem certeza que quer sair?",
            "Confirmação de Saída",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        if (response == JOptionPane.YES_OPTION) {

            System.clearProperty("nomeCompleto");
            System.clearProperty("matricula");
            System.clearProperty("email");
            System.clearProperty("cpf");
            System.clearProperty("celular");
            System.clearProperty("celularreserva");
            System.clearProperty("endereco");
            System.clearProperty("complemento");
            System.clearProperty("cep");
            System.clearProperty("senha");
            System.clearProperty("tipo");

            System.out.println("Logout realizado com sucesso!");

            dispose();
            TelaTipoLogin novaTela = new TelaTipoLogin();
            novaTela.setVisible(true);

        }

    }//GEN-LAST:event_mnSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimoBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimoBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimoBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimoBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimoBibliotecario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenuItem mnCadastroUExterno;
    private javax.swing.JMenuItem mnCadastroUInterno;
    private javax.swing.JMenu mnMenu;
    private javax.swing.JMenuItem mnMenuGerenciarAcervo;
    private javax.swing.JMenuItem mnMenuSolicitacoes;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenu mnUsuario;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tblEmprestimo;
    // End of variables declaration//GEN-END:variables
}
