package view.Bibliotecário;

import beans.pedido;
import dao.emprestimoDAO;
import dao.pedidoDAO;
import javax.swing.JOptionPane;

public class TelaSolicitacao extends javax.swing.JFrame {

private void configurarTela(pedido pedido) {
    
        // Configura a mensagem padrão para tipo de solicitação
        if (pedido.getTipoPedido().equals("EMPRESTIMO")) {
            
            System.out.println(pedido.getTipoPedido());
            tipoSolicitação.setText("SOLICITAÇÃO DE EMPRÉSTIMO");
            txtTempoExtensao.setVisible(false);
            txtPrazo.setVisible(false);
            
        } else{
            
            System.out.println(pedido.getTipoPedido());
            tipoSolicitação.setText("EXTENSÃO DE PRAZO");
            
            txtTempoExtensao.setVisible(true);
            txtPrazo.setText(Integer.toString(pedido.getExtensaoPrazo()));
            
        }

        // Configura o nome do usuário e o título do material
        txtUser.setText(pedido.getUserName());
        txtTituloMaterial.setText(pedido.getTitulo());
    }
    
    public TelaSolicitacao() {
        
        pedido pedido = new pedido();
        pedidoDAO pDAO = new pedidoDAO();
        pedido = pDAO.resgatarPedido();
        initComponents();
        configurarTela(pedido);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tipoSolicitação = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTempoExtensao = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        txtTituloMaterial = new javax.swing.JLabel();
        txtPrazo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAutorizar = new javax.swing.JButton();
        txtRejeitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PERGAMUM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Meditative", 0, 24))); // NOI18N

        tipoSolicitação.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoSolicitação.setText("Jlabel");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nome do solicitante");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Título do exemplar");

        txtTempoExtensao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTempoExtensao.setText("Tempo de extensão");

        txtUser.setText("jLabel5");

        txtTituloMaterial.setText("jLabel6");

        txtPrazo.setText("jLabel7");

        jLabel8.setText("Autorizar empréstimo/extensão de empréstimo?");

        txtAutorizar.setText("Autorizar");
        txtAutorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorizarActionPerformed(evt);
            }
        });

        txtRejeitar.setText("Rejeitar");
        txtRejeitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRejeitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtTituloMaterial))
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrazo)
                            .addComponent(txtTempoExtensao)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipoSolicitação)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRejeitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAutorizar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(183, 183, 183))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tipoSolicitação)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtTempoExtensao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser)
                    .addComponent(txtTituloMaterial)
                    .addComponent(txtPrazo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutorizar)
                    .addComponent(txtRejeitar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAutorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorizarActionPerformed
        
        pedido pedido = new pedido();
        pedidoDAO pDAO = new pedidoDAO();
        pedido = pDAO.resgatarPedido();
        emprestimoDAO eDAO = new emprestimoDAO();

        try{
            
            boolean sucesso = false;
            
            if( pedido.getTipoPedido().equals("EMPRESTIMO")){
                
                sucesso = eDAO.autorizarEmprestimo(pedido);
                if (sucesso) {
                    
                    JOptionPane.showMessageDialog(this, "O empréstimo foi autorizado com sucesso!");
                    
                } else {
                    
                    JOptionPane.showMessageDialog(this, "Houve um problema ao registrar o empréstimo.");
                    
                }
                
            } else {
                
                sucesso = eDAO.estenderPrazo(pedido);
                
                if (sucesso) {
               
                    JOptionPane.showMessageDialog(this, "A extensão do empréstimo foi autorizada com sucesso!");
                
                } else {
                    
                    JOptionPane.showMessageDialog(this, "Houve um problema ao atualizar o prazo do empréstimo.");
                    
                }
            }

            if (sucesso) {
                
                pDAO.autorizarPedido(pedido);
                JOptionPane.showMessageDialog(this, "O status do pedido foi atualizado!");
                dispose();
            }
            
        }catch(Exception e){
            
            e.printStackTrace(); // Log do erro para depuração
            JOptionPane.showMessageDialog(this, "Ocorreu um erro durante o processo.");
            
        }
        
    }//GEN-LAST:event_txtAutorizarActionPerformed

    private void txtRejeitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRejeitarActionPerformed
       
        pedido pedido = new pedido();
        pedidoDAO pDAO = new pedidoDAO();
        pedido = pDAO.resgatarPedido();


        try{
            
            if( pedido.getTipoPedido().equals("EMPRESTIMO")){
                
                JOptionPane.showMessageDialog(this, "O empréstimo foi rejeitado com sucesso!.");
                pDAO.rejeitarPedido(pedido);
                JOptionPane.showMessageDialog(this, "O status do pedido foi atualizado!.");
                dispose();  
                
            }else{
               
               JOptionPane.showMessageDialog(this, "A extensão do empréstimo foi rejeitada com sucesso!.");
               pDAO.rejeitarPedido(pedido);
               JOptionPane.showMessageDialog(this, "O status do pedido foi atualizado!.");
               dispose(); 
               
            }
            
            
        }catch(Exception e){
            
            if(pedido.getTipoPedido().equals("EMPRESTIMO")){
                
                JOptionPane.showMessageDialog(this, "Houve um problema ao rejeitar o empréstimo.");
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Houve um problema ao rejeitar o prazo do empréstimo.");
                
            }
            
        }
        
    }//GEN-LAST:event_txtRejeitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSolicitacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tipoSolicitação;
    private javax.swing.JButton txtAutorizar;
    private javax.swing.JLabel txtPrazo;
    private javax.swing.JButton txtRejeitar;
    private javax.swing.JLabel txtTempoExtensao;
    private javax.swing.JLabel txtTituloMaterial;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
